import Head from "next/head";
import { fetchposts } from "../redux/actions/fetchPosts";
import { GetServerSideProps } from "next";
import { useRouter } from 'next/router'


import store from "../redux/store";
import Post from "../components/Post/Post";
import React from "react";
import { Container } from "../styled/global";

export default function Home({ all_posts }: any) {
  const router = useRouter()

  const posts = all_posts.posts.posts;

  const viewWholePost = (e: { preventDefault: () => void; }, id : number) => {
    e.preventDefault();
    localStorage.setItem('postId', JSON.stringify(id))
    router.push('/posts/'+id)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container top={100}>
        {[...posts, { addPost: true, id: -1 }].map((el: any) => {
          if (el.addPost) {
            return (
              <Post key={el.id} onClick={() => router.push('/posts/new')}>
                <Post.Title style={{ textAlign: "center" }}>
                  <button>ADD ONE</button>
                </Post.Title>
                <Post.Body style={{ textAlign: "center" }}>
                  Do you want to add your own post?
                </Post.Body>
              </Post>
            );
          }
          return (
            <Post key={el.id} onClick={(e: { preventDefault: () => void; }) => viewWholePost(e, el.id)}>
              <Post.Title>{el.title}</Post.Title>
              <Post.Body>{el.body}</Post.Body>
            </Post>
          );
        })}
      </Container>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (
  context: any,
) : Promise<any> => {
  await store.dispatch(fetchposts());
  return {
    props: { all_posts: store.getState() },
  };
};
